name: Deploy Spring Boot App to Elastic Beanstalk
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the application
        run: mvn clean package -DskipTests

      - name: Find built JAR file
        id: jar
        run: echo "JAR_FILE=$(ls target/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Verify JAR built
        run: ls -lh target

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.run_id }}
          deployment_package: ${{ env.JAR_FILE }}
